# Generated by Django 5.2.3 on 2026-05-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AddField(
            model_name='message',
            name='auto_delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
