# Generated by Django 5.2.3 on 2026-05-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_options_message_auto_delete_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_messages_sent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_rooms_created',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
