name: Deploy RITA App

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 56.228.72.135 
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/rita_app
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py collectstatic --noinput
            sudo systemctl restart rita
